services:
  pyfaceserve:
    image: heronq02/pyfaceserve:v1.0.0
    environment:
      - TRITON_URL=localhost:6000
      - DETECTION_NAME=yolov7-hf-v1
      - SPOOFING_NAME=spoofer
      - RECOGNITION_NAME=ghostfacenet
      - DETECTION_THRESH=0.7
      - SPOOFING_THRESH=0.4
      - RECOGNITION_THRESH=0.4
      - QDRANT_URL=localhost:6333
      - IMG_DIR=face_images
    volumes:
      - ${PWD}/face_images:/face_images
    network_mode: "host"
    depends_on:
      triton:
        condition: service_healthy
    command: fastapi run main.py --port 5999

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ${PWD}/qdrant_hub:/qdrant/storage
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      interval: 10s
      timeout: 5s
      retries: 2

  triton:
    # image: hieupth/tritonserver:cpuext
    image: nvcr.io/nvidia/tritonserver:24.04-py3
    volumes:
      - ${PWD}/models:/models
    ports:
      - "6000:6000"
      - "6001:6001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/v2/health/ready"]
      interval: 60s
      timeout: 5s
      retries: 2
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['1']
    #         capabilities: [gpu]
    command: tritonserver --model-repository=/models --http-port 6000 --grpc-port 6001

    